### ISSUE TITLE
[Bug] The login feature doesn't work.

### ISSUE THREAD

**Issue by longnd** [Vivek-sudo/nimble-assessment.backend#11]
## Issue

The login feature doesn't work.

https://github.com/21jake/nimble-scraper/assets/1896814/b0dc2038-815a-4b56-869d-55a5b3a3b0f8

The token is not set to Local Storage.

## Expected
- Fill in the correct credential will log the user in to the system

## Steps To Reproduce
- Navigate to the homepage: localhost:3000
- Fill in the correct username & password
- The user is navigated back to the login page.

**Comment by Vivek-sudo** [comment]
Raised PR to fix this: https://github.com/Vivek-sudo/nimble-assessment.client/pull/3

**Comment by longnd** [comment]
Thank you for the fix. I have reviewed the fix.
